# Thêm dòng này để cấu hình SDK Firebase:
$FirebaseSDKVersion = '7.0.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Sửa lỗi [!] [Xcodeproj] Generated duplicate UUIDs:
# inhibit_all_warnings!

# [!] [Xcodeproj] Generated duplicate UUIDs:
# @see http://stackoverflow.com/a/33440077/456536
# A:
#   export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES
# B:
#   install! 'cocoapods', :deterministic_uuids => false

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '10.0'


target 'rn_base' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
   # Cấu hình Permission:
   permissions_path = '../node_modules/react-native-permissions/ios'
   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
   pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  # Cấu hình Map:
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Cấu hình firebase:
  pod 'Firebase/Analytics'
  
   # Cấu hình Youtobe:
   pod 'XCDYouTubeKit', '~> 2.8'

   # Cấu hình Codepush:
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'rn_baseTests' do
    inherit! :complete
    # Pods for testing
  end
  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rn_base-tvOS' do
  # Pods for rn_base-tvOS

  target 'rn_base-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


