# Thêm dòng này để cấu hình SDK Firebase:
$FirebaseSDKVersion = '7.0.0'

platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# [!BUG] [Xcodeproj] Generated duplicate UUIDs: http://stackoverflow.com/a/33440077/456536
install! 'cocoapods', :deterministic_uuids => false

target 'rn_base' do
# Từ bản 0.62 sẽ cập nhật Trình gỡ lỗi Flipper:
# https://fbflipper.com/docs/getting-started/react-native-ios
# https://reactnative.thenativebits.com/courses/upgrading-react-native/upgrade-to-react-native-0.62/
# Flipper là công cụ gỡ lỗi mã nguồn mở của Facebook cho các ứng dụng di động.
# Nó có nhiều tính năng hữu ích như trình kiểm tra mạng, kiểm tra bố cục, trình xem nhật ký và tích hợp với metro để cho phép tải lại ứng dụng của bạn mà không làm rung thiết bị của bạn.
# Flipper được hỗ trợ trong React Native 0.61, tuy nhiên, việc thiết lập cho iOS sẽ hơi khó khăn vì xung đột với các phiên bản của Yoga Cocoapod đã được sử dụng ( Yoga là công cụ bố cục flexbox của React Native).
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

   # Cấu hình Permission:
   permissions_path = '../node_modules/react-native-permissions/ios'
   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
   pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
   pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  # Cấu hình firebase:
  pod 'Firebase/Analytics'

  # Cấu hình Map:
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Cấu hình Youtobe:
   pod 'XCDYouTubeKit', '~> 2.8'

  # Cấu hình code Push:
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # Các cấu hình thư viện khác:
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  
   # Cấu hình FB-sdk:
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', :modular_headers => true
  pod 'FBSDKLoginKit', :modular_headers => true
  pod 'FBSDKShareKit', :modular_headers => true
  pod 'GoogleSignIn', :modular_headers => true

  use_modular_headers!
  use_native_modules!

  target 'rn_baseTests' do
    inherit! :complete
  end
end
