const KEY_NAVIGATION = {
  auth_navigator: 'AUTH_NAVIGATOR',
  main_navigator: 'MAIN_NAVIGATOR',
  app_intro: 'APP_INTRO',
  home: 'HOME',
  login: 'LOGIN',
  policy: 'POLICY',
  entry: 'ENTRY',
  drawer: 'DRAWER',
  webview: 'WEBVIEW',
  location: 'LOCATION',
  video: 'VIDEO',
  map: 'MAP',
  notification: 'NOTIFICATION',
  qr: 'QR',
  youtobe: 'YOUTOBE',
  notification_detail: 'NOTIFICATION_DETAIL',
  video_detail_android: 'VIDEO_DETAIL_ANDROID',
  direction_map: 'DIRECTION_MAP',
};
export {KEY_NAVIGATION};
