const KEY_NAVIGATION = {
  //TAB_VIEW_HOME_MENU:
  auth_navigator: 'AUTH_NAVIGATOR',
  main_navigator: 'MAIN_NAVIGATOR',
  app_intro: 'APP_INTRO',
  home: 'HOME',
  login: 'LOGIN',
  policy: 'POLICY',
  entry: 'ENTRY',
  drawer: 'DRAWER',
  webview: 'WEBVIEW',
  location: 'LOCATION',
  video: 'VIDEO',
  map: 'MAP',
  notification: 'NOTIFICATION',
  qr: 'QR',
  youtobe: 'YOUTOBE',
  notification_detail: 'NOTIFICATION_DETAIL',
  video_detail_android: 'VIDEO_DETAIL_ANDROID',
  direction_map: 'DIRECTION_MAP',
  animation: 'ANIMATION',
  youtube_ads: 'YOUTUBE_ADS',
  firebase_auth: 'FIRE_BASE_AUTHENTICATION',
  download_img: 'DOWNLOAD_IMG',
  light_screen: 'LIGHT_SCREEN',
  upload_images: 'UPLOAD_IMAGES',
  //TAB_VIEW_LIBRARY:
  library_push_local: 'PUSH_LOCAL_SCHEDULED',
};
export {KEY_NAVIGATION};
